### ISSUE TITLE
break on line 176

### ISSUE THREAD

**Issue by linkedtothefuture** [paralelo14/google_explorer#34]
Why is there a break on line 176. I couldn't understand.

**Comment by Adeka-UAR** [comment]
could give us more info, please.

**Comment by paralelo14** [comment]
Sorry my friends... i'm very busy for the last month...

This point of the code you are asking is because depending of the location of the user is making the search, the xpath for the option can change... so i try the first option if it finds it it breaks and continue... if he don't find on the first time it try the second option for that xpath location..

something like this:
Try option 1:
  find it? Yes, break..
Try option 2:
 find it? Yes, break.

**Comment by paralelo14** [comment]
its a for loop on the options and breaks when find.. =)

**Comment by linkedtothefuture** [comment]
wouldn't it be easier to understand like this ?

`    def go_to_advanced_search_page(self):
        time.sleep(2)
        driver = self.driver
        try:
            driver.find_element(By.XPATH, "//*[@id='ab_opt_icon']").click()
            time.sleep(1)
            driver.find_element(By.XPATH, "//*[@id='ab_as" "and @href[contains(.,'/advanced_search')]]"]).click()
        except:
            driver.find_element(By.XPATH, "//*[@id='abar_button_opt']").click()
            time.sleep(1)
            driver.find_element(By.XPATH, ]"//*[@id='abar_button_opt']", 'advanced_search_option': "//div/" "a[contains(@href,'advanced')"].click()`

**Comment by linkedtothefuture** [comment]
sorry ... browser problem ...

like this.


[go_to_advanced_search_page.txt](https://github.com/anarcoder/google_explorer/files/1061365/go_to_advanced_search_page.txt)

**Comment by paralelo14** [comment]
Nop...

The reason is why in a loop is for any reason google changes the path to go to the advanced page, the solution will be only put another element on that dictionary..

On your code, appears be more simple just put 2 options in a try except... but on the situation of more options won't work...

best regards,

daniel.

**Comment by Boris519** [comment]
By my side 

`File` "google_explorer.py", line 248
    `time.sleep(2)`
